name: Python continuous Integration
on : 
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  python-job:
    name: python job
    runs-on : ubuntu-latest
    container: python:3.8.10
    steps:
     - run: python --version
       name: Check python version
     - uses: actions/checkout@v3
       name: Check outcode
     - run: pip install -r requirements.txt
       name: Installing requirements
     - run: python main.py
       name: Run main.py