name: Python continuous Integration
on : push
jobs:
  python-job:
    name: python job
    runs-on : ubuntu-latest
    container: python:3.8.10
    steps:
     - run: python --version
       name: Check python version
     - run: python main.py
       name: Run main.py